dataset_config:
  hateful_memes:
    use_images: true
    use_features: false
    # Disable this in your config if you do not need features info
    # and are running out of memory
    return_features_info: true
